### ISSUE TITLE
CJB Cheat Menu Not Working! Please Help!

### ISSUE THREAD

**Issue by KnIXght** [Pathoschild/SMAPI#204]
Sorry if this is not the place to be posting this. I am new here. However, I just needed help with this error code. Stardew Valley opens and runs fine, but this error pops up when I press P;

[17:06:58 INFO  SMAPI] SMAPI 1.4 with Stardew Valley 1.11 on Microsoft Windows NT 6.2.9200.0
[17:06:58 DEBUG SMAPI] Loading SMAPI...
[17:06:58 DEBUG SMAPI] Loading game...
[17:06:58 DEBUG SMAPI] Loading mods...
[17:06:58 TRACE SMAPI] CJB Cheats Menu used Manifest.Authour, which is deprecated since SMAPI 1.0. This will break in a future version of SMAPI.
[17:06:58 INFO  SMAPI] Loaded mod: CJB Cheats Menu by CJ Bok, v1.12 | Simple in-game cheats menu!
[17:06:58 TRACE SMAPI] CJB Cheats Menu used the Config class, which is deprecated since SMAPI 1.0. This will break in a future version of SMAPI.
[17:06:58 TRACE SMAPI] CJB Cheats Menu used an old version of Mod.Entry, which is deprecated since SMAPI 1.0. This will break in a future version of SMAPI.
[17:06:58 INFO  SMAPI] Loaded mod: Trainer Mod by Zoryn, v1.0 | Registers several commands to use. Most commands are trainer-like in that they offer forms of cheating.
[17:06:58 DEBUG SMAPI] Loaded 2 mods.
[17:06:58 DEBUG SMAPI] Starting game...
[17:06:58 DEBUG SMAPI] Starting console...
[17:06:58 INFO  SMAPI] Type 'help' for help, or 'help <cmd>' for a command's usage
[17:07:24 ERROR SMAPI] A mod failed handling the ControlEvents.KeyPressed event:
System.MissingMethodException: Method not found: 'Void StardewValley.Menus.ClickableTextureComponent..ctor(Microsoft.Xna.Framework.Rectangle, System.String, System.String, Microsoft.Xna.Framework.Graphics.Texture2D, Microsoft.Xna.Framework.Rectangle, Single)'.
   at CJBCheatsMenu.CheatsMenu..ctor(Int32 x, Int32 y, Int32 width, Int32 height)
   at CJBCheatsMenu.CheatsMenu.Open()
   at CJBCheatsMenu.Cheats.onKeyPress(Keys key)
   at CJBCheatsMenu.CJBCheatsMenu.Events_KeyPressed(Object sender, EventArgsKeyPressed e)
   at StardewModdingAPI.Framework.InternalExtensions.SafelyRaiseGenericEvent[TEventArgs](IMonitor monitor, String name, IEnumerable`1 handlers, Object sender, TEventArgs args) in D:\source\_Stardew\SMAPI\src\StardewModdingAPI\Framework\InternalExtensions.cs:line 57

**Comment by Pathoschild** [comment]
For reference, the official version doesn't work with the latest version of the game. Try using [this unofficial version instead](http://community.playstarbound.com/threads/125031/).
