### ISSUE TITLE
SMAPI fails to load some mod dependency DLLs

### ISSUE THREAD

**Issue by Krutonium** [Pathoschild/SMAPI#207]
```
[17:52:59 INFO  SMAPI] Loaded mod: Stardew Keys by Krutonium, v1.0 | Adds support for Logitech Keyboard LED's to Stardew Valley
[17:52:59 INFO  Stardew Keys] Loading...
[17:52:59 ERROR SMAPI] Couldn't load mod for manifest 'E:\Steam\steamapps\common\Stardew Valley\Mods\StardewKeys\manifest.json': an error occurred while loading the target DLL.
System.DllNotFoundException: Unable to load DLL 'LogitechLedEnginesWrapper ': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at LedCSharp.LogitechGSDK.LogiLedInit()
   at StardewKeys.ModEntry.Entry(IModHelper helper)
   at StardewModdingAPI.Program.LoadMods() in D:\source\SMAPI\src\StardewModdingAPI\Program.cs:line 459
```

The DLL is of course, not a valid SMAPI mod in the first place. Any way to tell SMAPI to ignore it/register it as a dependency of my mod?

**Comment by Pathoschild** [comment]
SMAPI preprocesses all assemblies in the mod directory to support crossplatform compatibility. For most imported assemblies that should consist of checking whether it references Stardew Valley or XNA/MonoGame, and if not just caching the fact that it doesn't.

It looks like that isn't happening properly here. Can you attach a zip containing the mod directory (the one with `manifest.json` and both DLLs)?

**Comment by Pathoschild** [comment]
@PFCKrutonium I'll close this for now due to lack of response. Feel free to reopen if you can provide a mod that reproduces the issue.

**Comment by theminerfromhell** [comment]
[stardew valley expansion.zip](https://github.com/Pathoschild/SMAPI/files/1176306/stardew.valley.expansion.zip)
this is giving me the same error, but i am on 1.6 since i havent updated my game in a while.

**Comment by theminerfromhell** [comment]
smapi 1.6 that is
stardew valley 1.1 just incase anyone is wondering

**Comment by theminerfromhell** [comment]
it was a bit different now that i check, so ill post my errror.

[18:35:53 ERROR SMAPI] Couldn't load mod for manifest 'C:\GOG Games\Stardew Valley\Mods\StardewValleyExpansion\manifest.json': manifest doesn't specify an entry DLL.
