### ISSUE TITLE
Closes on Killing Monster

### ISSUE THREAD

**Issue by Bremusa** [Pathoschild/SMAPI#223]
I'm completely new to coding, reading and understanding but I *think* it might be a SMAPI error? If not, could you point me in the right direction.

Here's the log:

[10:04:18 ERROR SMAPI] An error occured in the base update loop: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at StardewValley.Debris..ctor(Int32 objectIndex, Vector2 debrisOrigin, Vector2 playerPosition)
   at StardewValley.GameLocation.monsterDrop(Monster monster, Int32 x, Int32 y)
   at StardewValley.Locations.MineShaft.monsterDrop(Monster monster, Int32 x, Int32 y)
   at StardewValley.GameLocation.damageMonster(Rectangle areaOfEffect, Int32 minDamage, Int32 maxDamage, Boolean isBomb, Single knockBackModifier, Int32 addedPrecision, Single critChance, Single critMultiplier, Boolean triggerMonsterInvincibleTimer, Farmer who)
   at StardewValley.Tools.MeleeWeapon.DoDamage(GameLocation location, Int32 x, Int32 y, Int32 facingDirection, Int32 power, Farmer who)
   at StardewValley.Farmer.showSwordSwipe(Farmer who)
   at StardewValley.FarmerSprite.currentAnimationTick()
   at StardewValley.FarmerSprite.animateOnce(GameTime time)
   at StardewValley.FarmerSprite.checkForSingleAnimation(GameTime time)
   at StardewValley.Farmer.Update(GameTime time, GameLocation location)
   at StardewValley.Game1.UpdateCharacters(GameTime time)
   at StardewValley.Game1.Update(GameTime gameTime)
   at StardewModdingAPI.Inheritance.SGame.Update(GameTime gameTime) in D:\source\_Stardew\SMAPI\src\StardewModdingAPI\Inheritance\SGame.cs:line 338

**Comment by Pathoschild** [comment]
Hi @Bremusa. That problem is usually caused by outdated XNB mods or corrupted game files. Try [verifying the game integrity](https://support.steampowered.com/kb_article.php?ref=2037-QEUH-3335) to fix that. Note that any XNB mods will be removed (but SMAPI mods won't be affected).

If you need more help, come talk [on Discord](https://discord.gg/kH55QXP) or [in the forums](http://community.playstarbound.com/threads/smapi-stardew-modding-api.108375). :)
