### ISSUE TITLE
System.MissingMethodException

### ISSUE THREAD

**Issue by domznil** [Pathoschild/SMAPI#235]
need help please:

[07:56:28 INFO  SMAPI] SMAPI 1.8 with Stardew Valley 1.1 on Microsoft Windows NT 6.2.9200.0
[07:56:29 DEBUG SMAPI] Mods go here: C:\GOG Games\Stardew Valley\Mods
[07:56:29 DEBUG SMAPI] Loading SMAPI...
[07:56:29 DEBUG SMAPI] Loading game...
[07:56:29 DEBUG SMAPI] Loading mods...
[07:56:30 TRACE SMAPI] Loading StardewValleyMP.dll...
[07:56:30 INFO  SMAPI] Loaded mod: Makeshift Multiplayer by spacechase0, v0.2.10 | Multiplayer test
[07:56:30 TRACE SMAPI] Loading TrainerMod.dll...
[07:56:30 INFO  SMAPI] Loaded mod: Trainer Mod by Zoryn, v1.0 | Registers several commands to use. Most commands are trainer-like in that they offer forms of cheating.
[07:56:30 TRACE SMAPI] Makeshift Multiplayer used Manifest.Authour, which is deprecated since SMAPI 1.0. This will break in a future version of SMAPI.
[07:56:30 TRACE SMAPI] Makeshift Multiplayer used the Log class, which is deprecated since SMAPI 1.1. This will break in a future version of SMAPI.
[07:56:30 DEBUG Makeshift Multiplayer] Loading Config
[07:56:30 TRACE SMAPI] Makeshift Multiplayer used the Config class, which is deprecated since SMAPI 1.0. This will break in a future version of SMAPI.
[07:56:30 TRACE SMAPI] Makeshift Multiplayer used Mod.Entry(object[]) instead of Mod.Entry(IModHelper), which is deprecated since SMAPI 1.0. This will break in a future version of SMAPI.
[07:56:30 DEBUG SMAPI] Loaded 2 mods.
[07:56:30 DEBUG SMAPI] Starting game...
[07:56:31 DEBUG SMAPI] Starting console...
[07:56:31 INFO  SMAPI] Type 'help' for help, or 'help <cmd>' for a command's usage
[07:56:42 ERROR SMAPI] An error occured in the base update loop: System.MissingMethodException: Method not found: 'StardewValley.NPC StardewValley.Game1.getCharacterFromName(System.String, Boolean)'.
   at StardewValleyMP.Vanilla.NewSaveGame.<getLoadEnumerator>d__1.MoveNext()
   at StardewValley.Game1.UpdateTitleScreen(GameTime time) in C:\Users\tomc\Documents\Visual Studio 2010\Projects\Stardew.XNA\Farmer\Farmer\Game1.cs:line 2147
   at StardewValley.Game1.Update(GameTime gameTime) in C:\Users\tomc\Documents\Visual Studio 2010\Projects\Stardew.XNA\Farmer\Farmer\Game1.cs:line 1612
   at StardewModdingAPI.Inheritance.SGame.Update(GameTime gameTime) in D:\source\_Stardew\SMAPI\src\StardewModdingAPI\Inheritance\SGame.cs:line 338

**Comment by Pathoschild** [comment]
Hi @domznil. Updating to the latest Stardew Valley 1.11 should fix that error.
