### ISSUE TITLE
System.MissingFieldException

### ISSUE THREAD

**Issue by JerryHellbound** [Pathoschild/SMAPI#240]
So i tried to install SMAPI, but even with no mods on. It still had this problem, i installed everything in the redist folder even. I dont know what i can do, all i can see is that theres a missing file, but im sure im wrong.
The errorlog is the following.
```
[14:39:02 INFO  SMAPI] SMAPI 1.8 with Stardew Valley 1.2.6 on Microsoft Windows NT 6.2.9200.0
[14:39:06 DEBUG SMAPI] Mods go here: C:\Program Files (x86)\Stardew Valley\Mods\
[14:39:06 DEBUG SMAPI] Loading SMAPI...
[14:39:06 DEBUG SMAPI] Loading game...
[14:39:06 DEBUG SMAPI] Loading mods...
[14:39:06 TRACE SMAPI] Loading TrainerMod.dll...
[14:39:06 INFO  SMAPI] Loaded mod: Trainer Mod by Zoryn, v1.0 | Registers several commands to use. Most commands are trainer-like in that they offer forms of cheating.
[14:39:06 DEBUG SMAPI] Loaded 1 mods.
[14:39:06 DEBUG SMAPI] Starting game...
[14:39:06 DEBUG SMAPI] Starting console...
[14:39:06 INFO  SMAPI] Type 'help' for help, or 'help <cmd>' for a command's usage
[14:39:08 ERROR SMAPI] The game encountered a fatal error:
System.MissingFieldException: Field not found: 'StardewValley.Game1.activeClickableMenu'.
   at StardewModdingAPI.Inheritance.SGame.UpdateEventCalls()
   at StardewModdingAPI.Inheritance.SGame.Update(GameTime gameTime) in D:\source\_Stardew\SMAPI\src\StardewModdingAPI\Inheritance\SGame.cs:line 329
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Microsoft.Xna.Framework.Game.Run()
   at StardewModdingAPI.Program.StartGame() in D:\source\_Stardew\SMAPI\src\StardewModdingAPI\Program.cs:line 284
```

**Comment by Pathoschild** [comment]
Hi @JerryHellbound. You have Stardew Valley 1.2 beta because you're on the Steam beta channel. You should use [SMAPI 1.9 beta](https://github.com/Pathoschild/SMAPI/releases) if you want to use mods with that version. Note that some mods aren't compatible with the beta version of the game yet.

**Comment by JerryHellbound** [comment]
Thank you 😃 It worked

**Comment by JerryHellbound** [comment]
Thank you 😃
