### ISSUE TITLE
SMAPI ERROR

### ISSUE THREAD

**Issue by onsidekiller** [Pathoschild/SMAPI#311]
I have the most updated stardew valley and SMAPI but i get this error. 
[12:47:39` INFO  SMAPI] SMAPI 1.14 with Stardew Valley 1.2.30 on Microsoft Windows 7 Home Premium 
[12:47:39 DEBUG SMAPI] Mods go here: C:\Program Files (x86)\Steam\steamapps\common\Stardew Valley\Mods
[12:47:39 DEBUG SMAPI] Preparing SMAPI...
[12:47:39 DEBUG SMAPI] Starting game...
[12:47:41 ERROR SMAPI] The game failed unexpectedly: System.Runtime.InteropServices.SEHException (0x80004005): External component has thrown an exception.
   at new[](UInt32 )
   at Microsoft.Xna.Framework.Audio.UnsafeNativeMethods.AllocateArrayAndReadFile(String filename, Void** ppData, UInt32* pdwBufferSize)
   at Microsoft.Xna.Framework.Audio.UnsafeNativeMethods.WaveBank.CreateHandle(UInt32 hEngine, String string, Int32 length, IntPtr& pCleanup)
   at Microsoft.Xna.Framework.Audio.WaveBank..ctor(AudioEngine audioEngine, String nonStreamingWaveBankFilename)
   at StardewValley.Game1.Initialize()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Microsoft.Xna.Framework.Game.Run()
   at StardewModdingAPI.Program.RunInteractively() in D:\source\_Stardew\SMAPI\src\StardewModdingAPI\Program.cs:line 214
[12:47:41 INFO  SMAPI] Game has ended. Press any key to exit.

Any help is nice.

**Comment by Pathoschild** [comment]
@onsidekiller That error seems to happen when too many things are using memory while the game is starting. A few things you can try:
* Reboot your computer.
* Close browsers, music players, and any other open programs. (If that works, you can reopen them after the game starts.)
* If you use a music mod, remove it.

If you still need help, feel free to post a message in the [SMAPI support thread](http://community.playstarbound.com/threads/smapi-stardew-modding-api.108375); the GitHub issues are only for tracking development tasks. :)
