### ISSUE TITLE
Remove base.Entry() calls automatically

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/SMAPI#362]
SMAPI 2.0 changes `Mod::Entry` from virtual to abstract. Most mods are unaffected, but 15/197 tested SMAPI mods show an error like this due to `base.Entry()` calls:
```
SpaceCore failed on entry and might not work correctly. Technical details:
System.BadImageFormatException: Bad IL format.
   at StardewModdingAPI.Mod.Entry(IModHelper helper)
   at SpaceCore.SpaceCore.Entry(IModHelper helper) in G:\StardewValley\Mods\SpaceCore\SpaceCore.cs:line 26
   at StardewModdingAPI.Program.LoadMods(IModMetadata[] mods, JsonHelper jsonHelper, SContentManager contentManager) in D:\source\_Stardew\SMAPI\src\StardewModdingAPI\Program.cs:line 783
```
Add a rewriter to remove `base.Entry()` calls automatically.

**Comment by Pathoschild** [comment]
Done in `develop` for the upcoming 2.0 release.
