### ISSUE TITLE
SMAPI 2.0 or 2.1 crash on start

### ISSUE THREAD

**Issue by Sulfurous** [Pathoschild/SMAPI#392]
Hi,

Game was working fine a few days ago. Now it gives the following error message on start:

`[22:26:31 INFO  SMAPI] SMAPI 2.1 with Stardew Valley 1.2.33 on Microsoft Windows 8.1
[22:26:31 DEBUG SMAPI] Mods go here: N:\SteamLibrary\steamapps\common\Stardew Valley\Mods
[22:26:31 TRACE SMAPI] Log started at 2017-11-12T03:26:31 UTC
[22:26:31 TRACE SMAPI] Overriding content manager...
[22:26:31 TRACE SMAPI] Starting game...
[22:26:31 ERROR SMAPI] The game failed unexpectedly: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Microsoft.Xna.Framework.Graphics.EffectPass..ctor(ID3DXBaseEffect* parent, EffectTechnique technique, SByte* Pass, Int32 index)
   at Microsoft.Xna.Framework.Graphics.EffectPassCollection..ctor(ID3DXBaseEffect* parent, EffectTechnique technique, Int32 count)
   at Microsoft.Xna.Framework.Graphics.EffectTechnique..ctor(ID3DXBaseEffect* parent, Effect effect, SByte* technique)
   at Microsoft.Xna.Framework.Graphics.EffectTechniqueCollection..ctor(ID3DXBaseEffect* parent, Effect effect, Int32 count)
   at Microsoft.Xna.Framework.Graphics.Effect.InitializeHelpers()
   at Microsoft.Xna.Framework.Graphics.Effect.CreateEffectFromCode(GraphicsDevice graphicsDevice, Byte[] effectCode)
   at Microsoft.Xna.Framework.Graphics.Effect..ctor(GraphicsDevice graphicsDevice, Byte[] effectCode)
   at Microsoft.Xna.Framework.Graphics.SpriteBatch..ctor(GraphicsDevice graphicsDevice)
   at xTile.Display.XnaDisplayDevice..ctor(ContentManager contentManager, GraphicsDevice graphicsDevice)
   at StardewValley.Game1.Initialize()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Microsoft.Xna.Framework.Game.Run()
   at StardewModdingAPI.Program.RunInteractively() in C:\source\_Stardew\SMAPI\src\SMAPI\Program.cs:line 226
[22:26:31 INFO  SMAPI] Game has ended. Press any key to exit.
`
I tried with and without mods and still get the same.

Any help is welcome

**Comment by Pathoschild** [comment]
@Sulfurous Here's the important part:
> AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

Try [performing a memory test](https://www.howtogeek.com/260813/how-to-test-your-computers-ram-for-problems/) to check for issues with your computer's RAM. If it finds errors, you may need to replace the RAM. If no errors are found, post a message in the [SMAPI support thread](https://community.playstarbound.com/threads/smapi-stardew-modding-api.108375) with the same info you posted above, and mention the memory test results.
