### ISSUE TITLE
Mod update checks fail if one mod has invalid version

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/SMAPI#462]
Update checks fail if a mod has an invalid version:

```
[WARN SMAPI] Couldn't check for new mod versions. This won't affect your game, but you won't be notified of mod updates if this keeps happening.
[DEBUG SMAPI] System.FormatException: The input '1.6.8h' isn't a valid semantic version.
    at StardewModdingAPI.Common.SemanticVersionImpl..ctor(String version) in C:\source\_Stardew\SMAPI\src\SMAPI.Common\SemanticVersionImpl.cs:line 78
    at StardewModdingAPI.SemanticVersion..ctor(String version) in C:\source\_Stardew\SMAPI\src\SMAPI\SemanticVersion.cs:line 50
    at StardewModdingAPI.Program.<>c__DisplayClass26_0.<CheckForUpdatesAsync>b__0() in C:\source\_Stardew\SMAPI\src\SMAPI\Program.cs:line 632
```

See:
* [sample log](https://log.smapi.io/pfSZekDE)
* [sample mods](https://github.com/Pathoschild/SMAPI/files/1853607/Mods.zip)

**Comment by Pathoschild** [comment]
Fixed in `develop` for the upcoming SMAPI 2.5.5.
