### ISSUE TITLE
Game crashes when player falls asleep outside of house

### ISSUE THREAD

**Issue by mpcomplete** [Pathoschild/SMAPI#463]
Stack dump:

[10:12:58 ERROR SMAPI] An error occured in the overridden update loop: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at StardewValley.Game1.Update(GameTime gameTime)
   at StardewModdingAPI.Framework.SGame.Update(GameTime gameTime) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:line 257
[10:12:58 ERROR SMAPI] An error occured in the overridden update loop: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at StardewValley.Game1.Update(GameTime gameTime)
   at StardewModdingAPI.Framework.SGame.Update(GameTime gameTime) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:line 257
[10:12:58 ERROR SMAPI] An error occured in the overridden update loop: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at StardewValley.Game1.Update(GameTime gameTime)

Crash log: [SMAPI-crash.txt](https://github.com/Pathoschild/SMAPI/files/1863817/SMAPI-crash.txt)

**Comment by Pathoschild** [comment]
Hi @mpcomplete. That crash isn't caused by SMAPI itself (it's just showing the error). Can you [post that log to log.smapi.io](https://log.smapi.io/), then add a message in [the support thread](https://community.playstarbound.com/threads/smapi-stardew-modding-api.108375) or [on Discord](https://stardewvalleywiki.com/Modding:Community) with a link to it? We'll help you troubleshoot which mod is causing it there. :)
