### ISSUE TITLE
Cant Save

### ISSUE THREAD

**Issue by BrotherBurrito** [Pathoschild/SMAPI#528]
everytime i go to sleep it starts to save but never finishes

here is the report:
[SMAPI] An error occured in the overridden update loop: System.InvalidOperationException: There was an error generating the XML document. ---> System.InvalidOperationException: The type StardewValley.Characters.Junimo was not expected. Use the XmlInclude or SoapInclude attribute to specify types that are not known statically.
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write40_NPC(String n, String ns, NPC o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write82_CommunityCenter(String n, String ns, CommunityCenter o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write92_GameLocation(String n, String ns, GameLocation o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write136_SaveGame(String n, String ns, SaveGame o, Boolean isNullable, Boolean needType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationWriterSaveGame.Write137_SaveGame(Object o)
   --- End of inner exception stack trace ---
   at StardewValley.SaveGame.<Save>d__47.MoveNext()
   at StardewValley.Menus.SaveGameMenu.update(GameTime time)
   at StardewValley.Menus.ShippingMenu.update(GameTime time)
   at StardewValley.Game1.Update(GameTime gameTime)
   at StardewModdingAPI.Framework.SGame.Update(GameTime gameTime) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:line 311

**Comment by Pathoschild** [comment]
Hi @BrotherBurrito. If you have the Junimo Deposit Anywhere mod, don't complete the bundle from outside the community center. This is a limitation documented in the mod description.

Note that GitHub issues are only used for SMAPI development tasks. If you still need help, feel free to [ask on Discord](https://stardewvalleywiki.com/Modding:Community#Discord) or post in the [SMAPI support thread](https://community.playstarbound.com/threads/108375). :)
