### ISSUE TITLE
Crash on returning to farm in the late afternoon/evening

### ISSUE THREAD

**Issue by Jessicanity** [Pathoschild/SMAPI#563]
I'm pretty sure this is SMAPI issue, as it doesn't happen if I run the game without SMAPI. I was hoping the newest update would sort it, but it seems not. Basically, if I return to the farm in the evening the game crashes, be it returning from town, the forest, the mountains, or going back outside from the farmhouse. 

I also do have some .xnb mods, which don't appear in the mods folder, but they don't require SMAPI and again the game runs fine without SMAPI. I also was having these issues before installing them. 

However, in case it is relevant, the XNB mods are the updated version of A Less Yellow Stardew Valley [(here)](https://www.nexusmods.com/stardewvalley/mods/1387) and the Totally Tubular Toolkit [(here)](https://community.playstarbound.com/threads/custom-animal-breeds-toolkit-v0-6-1-2-now-with-lite-mode.112153/) for installing custom breeds with a save-editor, so you can have multiple custom breeds. 

Error log:
```
[15:09:27 ERROR SMAPI] An error occured in the overridden draw loop: System.NullReferenceException: Object reference not set to an instance of an object.
   at StardewModdingAPI.Framework.SGame.DrawImpl(GameTime gameTime) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:line 968
   at StardewModdingAPI.Framework.SGame.Draw(GameTime gameTime) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SGame.cs:line 729
[15:09:27 TRACE SMAPI] Recovering sprite batch from error...
[15:09:27 TRACE SMAPI] Disposing...
[15:09:27 TRACE SMAPI] Disposing the content coordinator. Content managers will no longer be usable after this point.
```

Mods folders and Save folder attached.

[Jess_190306304.zip](https://github.com/Pathoschild/SMAPI/files/2184461/Jess_190306304.zip)
[Mods.zip](https://github.com/Pathoschild/SMAPI/files/2184462/Mods.zip)

**Comment by Pathoschild** [comment]
That should be fixed in the latest versions of Stardew Valley and SMAPI (currently 1.3.24 and beta 20.1 respectively).

If it still happens after updating, come [ask in #modding on the Stardew Valley Discord](https://stardewvalleywiki.com/Modding:Community#Discord) or post in the [SMAPI support thread](https://community.playstarbound.com/threads/108375). (GitHub issues are only used for SMAPI development tasks.)
