### ISSUE TITLE
Newest version of Stardew Valley doesn't follow SemVer rules, crashes SMAPI

### ISSUE THREAD

**Issue by kschelonka** [Pathoschild/SMAPI#674]
**Describe the bug**
SMAPI fails to start due to invalid SemVer versioning in latest Stardew Update (1.4.0.1)

**Log File**
Error:
```
SMAPI failed to initialize: System.TypeInitializationException: The type initializer for 'StardewModdingAPI.Constants' threw an exception. ---> System.FormatException: The input '1.4.0.1' isn't a valid semantic version.
   at StardewModdingAPI.Toolkit.SemanticVersion..ctor(String version) in C:\source\_Stardew\SMAPI\src\SMAPI.Toolkit\SemanticVersion.cs:line 90
   at StardewModdingAPI.Framework.GameVersion..ctor(String version) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\GameVersion.cs:line 39
   at StardewModdingAPI.Constants..cctor() in C:\source\_Stardew\SMAPI\src\SMAPI\Constants.cs:line 92
   --- End of inner exception stack trace ---
   at StardewModdingAPI.Constants.get_GameVersion() in C:\source\_Stardew\SMAPI\src\SMAPI\Constants.cs:line 92
   at StardewModdingAPI.Program.AssertGameVersion() in C:\source\_Stardew\SMAPI\src\SMAPI\Program.cs:line 94
   at StardewModdingAPI.Program.Main(String[] args) in C:\source\_Stardew\SMAPI\src\SMAPI\Program.cs:line 40
Game has ended. Press any key to exit.
```

**Comment by Pathoschild** [comment]
Fixed in SMAPI 3.0.1 (and later Stardew Valley 1.4.1).
