### ISSUE TITLE
audio not working when using shortcut

### ISSUE THREAD

**Issue by ghost** [Pathoschild/SMAPI#788]
when i try to launch a shortcut of smapi with target
 C:\Windows\System32\cmd.exe /c start "" /High /Affinity 2 "E:\Stardew.Valley.v1.5.4\Stardew Valley\StardewModdingAPI.exe" 
it gives me an error 
[game] Game.Initialize() caught exception initializing XACT:
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Windows\system32\Content\XACT\FarmerSounds.xgs'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.Xna.Framework.Audio.AudioEngine..ctor(String settingsFile, TimeSpan lookAheadTime, String rendererId)
   at StardewValley.Game1.Initialize() in C:\GitlabRunner\builds\Gq5qA5P4\1\ConcernedApe\stardewvalley\Farmer\Farmer\Game1.cs:line 1805

and does not play audio
idk if it a windows bug 
it plays audio if i run StardewModdingAPI.exe as it is.
smapi error logs [SMAPI-latest.txt](https://github.com/Pathoschild/SMAPI/files/6647459/SMAPI-latest.txt)

**Comment by Pathoschild** [comment]
Hi! That's an unusual target, but we'd need to run some tests. GitHub issues are only used to track development tasks, so most of the users who help with support questions don't watch here. See [Modding:Help](https://stardewvalleywiki.com/Modding:Help) on the wiki for the best places to ask instead.
